#!/bin/env sh

termcolours() {
	if [[ "$TERM" = "screen"* ]] && [[ -n "$TMUX" ]]; then
	  if [ "$1" == "prod" ]; then
	    tmux select-pane -P 'bg=#350000'
	  elif [ "$1" == "dev" ]; then
	    tmux select-pane -P 'bg=#404000'
	  elif [ "$1" == "other" ]; then
	    tmux select-pane -P 'bg=#253320'
	  else
	    tmux select-pane -P 'bg=#1f2224'
	  fi;
	else
	  if [ "$1" == "prod" ]; then
	    printf '\033]11;#350000\007'
	  elif [ "$1" == "dev" ]; then
	    printf '\033]11;#404000\007'
	  elif [ "$1" == "other" ]; then
	    printf '\033]11;#253320\007'
	  else
	    printf '\033]11;#1f2224\007'
	  fi
	fi
}

color-ssh() {
	trap "termcolours" RETURN EXIT
        if [[ "$*" =~ "prod" ]]; then
	    termcolours prod
	elif [[ "$*" =~ "dev" ]]; then
	    termcolours dev
	else
	    termcolours other
	fi
	ssh $*
}

